### ISSUE TITLE
您好，介绍文档和数据集链接都失效了，请问能否再提供一次呢？

### ISSUE THREAD

**Issue by hulelewin** [WenMellors/BUAA-DL2021#32]

**Comment by WenMellors** [comment]
该项目的正式仓库为 https://github.com/LibCity/Bigscity-LibCity，您可以访问该仓库获取最新的代码。介绍信息可以查看该仓库 readme 的 tutorial 环节。数据集链接也在 readme 中。

**Comment by hulelewin** [comment]
你好，链接打开之后没有内容，出现错误

**Comment by WenMellors** [comment]
额，看起来是 github 莫名渲染，把后面的中文字也加到 url 里面了。 https://github.com/LibCity/Bigscity-LibCity
