### ISSUE TITLE
您好，请问可以给我分享一下大作业里用到的交通数据吗？

### ISSUE THREAD

**Issue by Freshine-jing** [WenMellors/BUAA-DL2021#33]
我是浙江大学计算机学院的学生，最近在研究交通预测相关的文章，碰巧看到了您的GitHub作业，想自己复现试试看，但是readme里提供的数据集链接已经失效了，请问您能给我提供一下之前作业的数据集吗？

**Comment by WenMellors** [comment]
您好，相关的工作我们整理成了 [LibCity](https://github.com/LibCity/Bigscity-LibCity) 工具库，可以去该项目下获取相应的开源数据。
